// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_trendfilter_RCPPEXPORTS_H_GEN_
#define RCPP_trendfilter_RCPPEXPORTS_H_GEN_

#include <RcppEigen.h>
#include <Rcpp.h>

namespace trendfilter {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("trendfilter", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("trendfilter", "_trendfilter_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in trendfilter");
            }
        }
    }

    inline NumericVector rcpp_tvd(NumericVector y, double lambda) {
        typedef SEXP(*Ptr_rcpp_tvd)(SEXP,SEXP);
        static Ptr_rcpp_tvd p_rcpp_tvd = NULL;
        if (p_rcpp_tvd == NULL) {
            validateSignature("NumericVector(*rcpp_tvd)(NumericVector,double)");
            p_rcpp_tvd = (Ptr_rcpp_tvd)R_GetCCallable("trendfilter", "_trendfilter_rcpp_tvd");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_rcpp_tvd(Shield<SEXP>(Rcpp::wrap(y)), Shield<SEXP>(Rcpp::wrap(lambda)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<NumericVector >(rcpp_result_gen);
    }

}

#endif // RCPP_trendfilter_RCPPEXPORTS_H_GEN_
