// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// f1step_test
List f1step_test(double y, Eigen::RowVectorXd Z, double H, Eigen::MatrixXd A, Eigen::MatrixXd RQR, Eigen::VectorXd a, Eigen::MatrixXd P);
RcppExport SEXP _trendfilter_f1step_test(SEXP ySEXP, SEXP ZSEXP, SEXP HSEXP, SEXP ASEXP, SEXP RQRSEXP, SEXP aSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::RowVectorXd >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< double >::type H(HSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type RQR(RQRSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type a(aSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(f1step_test(y, Z, H, A, RQR, a, P));
    return rcpp_result_gen;
END_RCPP
}
// df1step_test
List df1step_test(double y, Eigen::RowVectorXd Z, double H, Eigen::MatrixXd A, Eigen::MatrixXd RQR, Eigen::VectorXd a, Eigen::MatrixXd P, Eigen::MatrixXd Pinf, int rankp);
RcppExport SEXP _trendfilter_df1step_test(SEXP ySEXP, SEXP ZSEXP, SEXP HSEXP, SEXP ASEXP, SEXP RQRSEXP, SEXP aSEXP, SEXP PSEXP, SEXP PinfSEXP, SEXP rankpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::RowVectorXd >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< double >::type H(HSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type RQR(RQRSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type a(aSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type P(PSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Pinf(PinfSEXP);
    Rcpp::traits::input_parameter< int >::type rankp(rankpSEXP);
    rcpp_result_gen = Rcpp::wrap(df1step_test(y, Z, H, A, RQR, a, P, Pinf, rankp));
    return rcpp_result_gen;
END_RCPP
}
// kftf_cpp_test
Eigen::VectorXd kftf_cpp_test(Eigen::VectorXd y, int k, double lambda);
RcppExport SEXP _trendfilter_kftf_cpp_test(SEXP ySEXP, SEXP kSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(kftf_cpp_test(y, k, lambda));
    return rcpp_result_gen;
END_RCPP
}
// admm_single_lambda
Eigen::VectorXd admm_single_lambda(int n, const Eigen::VectorXd& y, const Eigen::ArrayXd& weights, int k, const Eigen::VectorXd& theta_init, const Eigen::SparseMatrix<double>& penalty_mat, const Eigen::SparseMatrix<double>& dk_mat, double lam, int max_iter, double rho, bool tridiag);
RcppExport SEXP _trendfilter_admm_single_lambda(SEXP nSEXP, SEXP ySEXP, SEXP weightsSEXP, SEXP kSEXP, SEXP theta_initSEXP, SEXP penalty_matSEXP, SEXP dk_matSEXP, SEXP lamSEXP, SEXP max_iterSEXP, SEXP rhoSEXP, SEXP tridiagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type penalty_mat(penalty_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type dk_mat(dk_matSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< bool >::type tridiag(tridiagSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_single_lambda(n, y, weights, k, theta_init, penalty_mat, dk_mat, lam, max_iter, rho, tridiag));
    return rcpp_result_gen;
END_RCPP
}
// admm_lambda_seq
Eigen::MatrixXd admm_lambda_seq(NumericVector x, Eigen::VectorXd y, Eigen::ArrayXd weights, int k, const Eigen::ArrayXd& lambda_seq, int max_iter, double rho_scale, bool tridiag);
RcppExport SEXP _trendfilter_admm_lambda_seq(SEXP xSEXP, SEXP ySEXP, SEXP weightsSEXP, SEXP kSEXP, SEXP lambda_seqSEXP, SEXP max_iterSEXP, SEXP rho_scaleSEXP, SEXP tridiagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::ArrayXd >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type lambda_seq(lambda_seqSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type rho_scale(rho_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type tridiag(tridiagSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_lambda_seq(x, y, weights, k, lambda_seq, max_iter, rho_scale, tridiag));
    return rcpp_result_gen;
END_RCPP
}
// admm_single_lambda_with_tracking
Rcpp::List admm_single_lambda_with_tracking(NumericVector x, Eigen::VectorXd& y, const Eigen::ArrayXd& weights, int k, double lam, int max_iter, double rho, bool tridiag);
RcppExport SEXP _trendfilter_admm_single_lambda_with_tracking(SEXP xSEXP, SEXP ySEXP, SEXP weightsSEXP, SEXP kSEXP, SEXP lamSEXP, SEXP max_iterSEXP, SEXP rhoSEXP, SEXP tridiagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< bool >::type tridiag(tridiagSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_single_lambda_with_tracking(x, y, weights, k, lam, max_iter, rho, tridiag));
    return rcpp_result_gen;
END_RCPP
}
// get_dk_mat
Eigen::SparseMatrix<double> get_dk_mat(int k, NumericVector xd, bool tf_weighting);
RcppExport SEXP _trendfilter_get_dk_mat(SEXP kSEXP, SEXP xdSEXP, SEXP tf_weightingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xd(xdSEXP);
    Rcpp::traits::input_parameter< bool >::type tf_weighting(tf_weightingSEXP);
    rcpp_result_gen = Rcpp::wrap(get_dk_mat(k, xd, tf_weighting));
    return rcpp_result_gen;
END_RCPP
}
// get_lambda_max
double get_lambda_max(const NumericVector& x, const Eigen::VectorXd& y, const Eigen::ArrayXd& weights, int k);
RcppExport SEXP _trendfilter_get_lambda_max(SEXP xSEXP, SEXP ySEXP, SEXP weightsSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(get_lambda_max(x, y, weights, k));
    return rcpp_result_gen;
END_RCPP
}
// get_lambda_seq
Eigen::ArrayXd get_lambda_seq(const NumericVector& x, const Eigen::VectorXd& y, const Eigen::ArrayXd& weights, int k, double lambda_min_ratio, int n_lambda);
RcppExport SEXP _trendfilter_get_lambda_seq(SEXP xSEXP, SEXP ySEXP, SEXP weightsSEXP, SEXP kSEXP, SEXP lambda_min_ratioSEXP, SEXP n_lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_min_ratio(lambda_min_ratioSEXP);
    Rcpp::traits::input_parameter< int >::type n_lambda(n_lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(get_lambda_seq(x, y, weights, k, lambda_min_ratio, n_lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_trendfilter_f1step_test", (DL_FUNC) &_trendfilter_f1step_test, 7},
    {"_trendfilter_df1step_test", (DL_FUNC) &_trendfilter_df1step_test, 9},
    {"_trendfilter_kftf_cpp_test", (DL_FUNC) &_trendfilter_kftf_cpp_test, 3},
    {"_trendfilter_admm_single_lambda", (DL_FUNC) &_trendfilter_admm_single_lambda, 11},
    {"_trendfilter_admm_lambda_seq", (DL_FUNC) &_trendfilter_admm_lambda_seq, 8},
    {"_trendfilter_admm_single_lambda_with_tracking", (DL_FUNC) &_trendfilter_admm_single_lambda_with_tracking, 8},
    {"_trendfilter_get_dk_mat", (DL_FUNC) &_trendfilter_get_dk_mat, 3},
    {"_trendfilter_get_lambda_max", (DL_FUNC) &_trendfilter_get_lambda_max, 4},
    {"_trendfilter_get_lambda_seq", (DL_FUNC) &_trendfilter_get_lambda_seq, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_trendfilter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
